version: '3'
services:
  graphite:
    image: 'graphiteapp/graphite-statsd'
    ports:
      - 8000:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8126:8126
      - 8125:8125
    volumes:
      - ./storage:/opt/graphite/storage
  portfolio:
    image: 'spotaddockers/portfolio:REPLACE_TAG'
    ports:
      - 80:80
      - 8080:3000
      - 3004:3004
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
