name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Manual TAG input'
        default: ''
        required: true

jobs:
  BuildDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set timestamp as release version - RELEASE_VERSION
        shell: bash

        run: |
          tag=${{ github.event.inputs.tag }}
          echo "REPOSITORY=spotaddockers/portfolio" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${tag}" >> $GITHUB_ENV

      - name: Deploy
        shell: bash
        run: |
          echo "${{ secrets.PORTFOLIO_PEM }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          sed -i 's/REPLACE_TAG/${{ env.RELEASE_VERSION }}/g' docker-compose.yml
          scp -i key.pem  -o "StrictHostKeyChecking no" docker-compose.yml ubuntu@54.158.249.202:/home/ubuntu/portfolio/
          ssh -i key.pem  -o "StrictHostKeyChecking no" ubuntu@54.158.249.202 'bash -s' < ./deploy.sh ${{ env.RELEASE_VERSION }}
