name: Main push trigger

on:
  push:
    branches:
      - main

jobs:
  BuildDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set timestamp as release version - RELEASE_VERSION
        shell: bash

        run: |
          echo "RELEASE_VERSION=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
          echo "REPOSITORY=spotaddockers/portfolio" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: spotaddockers
          password: ${{ secrets.DOCKER_PASS }}
    
#      - name: Docker build & push
#        shell: bash
#        run: |
#          docker build -t ${{ env.REPOSITORY }}:${{ env.RELEASE_VERSION }} .
#          docker push ${{ env.REPOSITORY }}:${{ env.RELEASE_VERSION }}

      - name: Deploy
        shell: bash
        run: |
          echo ${{ secrets.PORTFOLIO_PEM }} > /tmp/key.pem
          chmod 400 /tmp/key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem 'ubuntu@3.82.163.200' "pwd && whoami"
          rm /tmp/key.pem

#          echo "${{ secrets.PORTFOLIO_PEM }}" | tr -d '\r' > key.pem
#          chmod 400 key.pem
#          ssh -i key.pem  -o "StrictHostKeyChecking no" ubuntu@3.82.163.200 <<'ENDSSH'
#          pwd
#          ls

#          mkdir -p chart/${{ env.REPO_NAME }}/config
#          cp config/* chart/${{ env.REPO_NAME }}/config
#          helm upgrade --install --history-max 2 --namespace oe-b2b-evs-dv ${{ env.REPO_NAME }}release \
#            --set image.tag=${{ env.RELEASE_VERSION }} chart/${{ env.REPO_NAME }} -f chart/values-dv.yaml
